// 更新资金状态
export const UPDATE_CAPITALSTATE_DATA = 'UPDATE_CAPITALSTATE_DATA'

// 更新当前持仓
export const UPDATE_MARKET_DATA = 'UPDATE_MARKET_DATA'

// 更新当日订单
export const UPDATE_ORDER_DATA = 'UPDATE_ORDER_DATA'

// 移除订单
export const REMOVE_ORDER_FROM_ID = 'REMOVE_ORDER_FROM_ID'


// 更新交易信息
export const UPDATE_TRADE_DATA = 'UPDATE_TRADE_DATA'