// 更新资金状态
export const UPDATE_CAPITALSTATE_DATA = 'UPDATE_CAPITALSTATE_DATA'

// 更新当前持仓，不存在就插入
export const UPDATE_MARKET_DATA = 'UPDATE_MARKET_DATA'

// 更新已存在的持仓
export const UPDATE_EXIST_MARKET_DATA = 'UPDATE_EXIST_MARKET_DATA'

// 更新当日订单
export const UPDATE_ORDER_DATA = 'UPDATE_ORDER_DATA'

// 移除订单
export const REMOVE_ORDER_FROM_ID = 'REMOVE_ORDER_FROM_ID'


// 更新交易信息
export const UPDATE_TRADE_DATA = 'UPDATE_TRADE_DATA'

// 更新交易设置
export const UPDATE_TRADE_SETTING = 'UPDATE_TRADE_SETTING'

// 更新本地配置
export const UPDATE_LOCAL_CONFIG = 'UPDATE_LOCAL_CONFIG'

// 清理
export const CLEAR_CAPITALSTATE_DATA = 'CLEAR_CAPITALSTATE_DATA'
export const CLEAR_MARKET_DATA = 'CLEAR_MARKET_DATA'
export const CLEAR_ORDER_DATA = 'CLEAR_ORDER_DATA'
export const CLEAR_TRADE_DATA = 'CLEAR_TRADE_DATA'